    ;;
    ;; constants
    ;;
    (global $INT_MIN i32 (i32.const -2147483648))
    (global $INT_MAX i32 (i32.const 2147483647))

    (global $INT64_MIN i64 (i64.const -9223372036854775808))
    (global $INT64_MAX i64 (i64.const 9223372036854775807))

    (global $UINT32_MAX i32 (i32.const 4294967295))
    (global $UINT64_MAX i64 (i64.const 18446744073709551615))

    (global $FLOAT_MIN f32 (f32.const -0x1.ff933c78cdfadp+127))
    (global $FLOAT_MIN_POSITIVE f32 (f32.const 0x1.00fb32c6204c4p-126))
    (global $FLOAT_MAX f32 (f32.const 0x1.ff933c78cdfadp+127))
    (global $FLOAT_EPSILON f32 (f32.const 0x1.ff19e23a836fcp-24))
    (global $FLOAT_NaN f32 (f32.const 0x7FC00000))
    (global $FLOAT_INF f32 (f32.const 0x7F800000))
    (global $FLOAT_NEG_INF f32 (f32.const 0xFF800000))

    (global $DOUBLE_MIN f64 (f64.const -0x1.fdcf158adbb99p+1023))
    (global $DOUBLE_MIN_POSITIVE f64 (f64.const 0x1.0091177587f82p-1022))
    (global $DOUBLE_MAX f64 (f64.const 0x1.fdcf158adbb99p+1023))
    (global $DOUBLE_EPSILON f64 (f64.const 0x1.ffe5ab7e8ad5ep-53))
    (global $DOUBLE_NaN f64 (f64.const 0x7FF8000000000000))
    (global $DOUBLE_INF f64 (f64.const 0x7FF0000000000000))
    (global $DOUBLE_NEG_INF f64 (f64.const 0xFFF0000000000000))

    (global $PI f64 (f64.const 3.141592653589793))
    (global $E f64 (f64.const 2.718281828459045))

    ;;
    ;; functions
    ;;
    (func $print (export "print") (param $ptr i32)
        (call $__fd_write (i32.const 1) (local.get $ptr) (i32.const 0))
    )
    
    (func $println (export "println") (param $ptr i32)
        (call $__fd_write (i32.const 1) (local.get $ptr) (i32.const 1))
    )

    (func $printerr (export "printerr") (param $ptr i32)
        (call $__fd_write (i32.const 2) (local.get $ptr) (i32.const 1))
    )

    (func $exit_int (export "exit_int") (param $exitCode i32)
        (call $__exit (local.get $exitCode))
    )

    (func $exit_int_String (export "exit_int_String") (param $exitCode i32) (param $message i32)
        (call $printerr (local.get $message))
        (call $__exit (local.get $exitCode))
    )

    (func $assert_bool (export "assert_bool") (param $cond i32)
        (if (i32.eqz (local.get $cond))
            (then
                (call $exit_int_String (i32.const 1) (global.get $__default_assertion_error))
            )
        )
    )
    (func $assert_bool_String (export "assert_bool_String") (param $cond i32) (param $message i32)
        (if (i32.eqz (local.get $cond))
            (then
                (call $exit_int_String (i32.const 1) (local.get $message))
            )
        )
    )
    (func $prompt (export "prompt") (param $promptText i32) (result i32)
        (local $ptr i32)
        (call $print (local.get $promptText))
        (call $__read_stdin)
        (local.tee $ptr)
        (return)
    )

    (func $__str_indexOf (export "__str_indexOf") (param $char i32) (param $ptr i32) (result i32)
       (local $i i32)
       (local $curr i32)
       (local $start i32)
       (local $len i32)
       (local.set $start (i32.add (local.get $ptr) (i32.const 4)))
       (local.set $len (call $__str_length (local.get $ptr)))
       (loop $str_loop (block $exit__str_loop
        (if (i32.eq (local.get $len) (local.get $i))
            (then
                (br $exit__str_loop)
            )
        )
        (i32.load8_u (i32.add (local.get $start) (local.get $i)))
        (local.set $curr)
        (if (i32.eq (local.get $curr) (local.get $char))
            (then
                (return (local.get $i))
            )
        )
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $str_loop)
       ))
       (i32.const -1)
       (return)
    )

    (func $__str_contains_char (export "__str_contains_char") (param $char i32) (param $ptr i32) (result i32)
        (local $index i32)
        (call $__str_indexOf (local.get $char) (local.get $ptr))
        (i32.ne (i32.const -1))
        (return)
    )

    (func $__str_contains_String (export "__str_contains_String") (param $inner i32) (param $str i32) (result i32)
        (local $innerLen i32)
        (local $innerStart i32)
        (local $len i32)
        (local $start i32)
        (local $matchLen i32)
        (local $i i32)
        (local $j i32)
        (local.set $innerLen (call $__str_length (local.get $inner)))
        (local.set $len (call $__str_length (local.get $str)))
        (if (i32.lt_u (local.get $len) (local.get $innerLen))
            (then (return (i32.const 0)))
        )
        (local.set $innerStart (i32.add (local.get $inner) (i32.const 4)))
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (loop $outerloop (block $exit_outerloop
            (i32.eq (local.get $i) (local.get $len))
            (br_if $exit_outerloop)
            (if (i32.eq (local.get $matchLen) (local.get $innerLen))
                (then (return (i32.const 1)))
            )
            (i32.load8_u (i32.add (local.get $start) (local.get $i)))
            (i32.load8_u (local.get $innerStart))
            (if (i32.eq)
                (then
                    (local.set $matchLen (i32.const 1))
                    (local.set $j (i32.add (local.get $i) (i32.const 1)))
                    (loop $innerLoop (block $exit_innerLoop
                        (i32.eq (local.get $j) (local.get $len))
                        (br_if $exit_innerLoop)
                        (if (i32.eq (local.get $matchLen) (local.get $innerLen))
                            (then (return (i32.const 1)))
                        )
                        (if (i32.ne 
                            (i32.load8_u (i32.add (local.get $start) (local.get $j)))
                            (i32.load8_u (i32.add (local.get $innerStart) (local.get $matchLen)))
                        )
                            (then
                                (local.set $matchLen (i32.const 0))
                                (br $exit_innerLoop)
                            )
                        )
                        (local.set $matchLen (i32.add (local.get $matchLen) (i32.const 1)))
                        (local.set $j (i32.add (local.get $j) (i32.const 1)))
                        (br $innerLoop)
                    ))
                )
            )
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $outerloop)
        ))
        (i32.eq (local.get $matchLen) (local.get $innerLen))
    )

    (func $__str_reverse (export "__str_reverse") (param $str i32) (result i32)
        (local $reversed i32)
        (local $start i32)
        (local $rstart i32)
        (local $len i32)
        (local $i i32)
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (local.set $len (call $__str_length (local.get $str)))
        (local.set $i (i32.sub (local.get $len) (i32.const 1)))
        (call $__malloc (i32.add (local.get $len) (i32.const 4)))
        (local.set $reversed)
        (local.set $rstart (i32.add (local.get $reversed) (i32.const 4)))
        (i32.store (local.get $reversed) (local.get $len))
        (loop $str_loop (block $exit_str_loop
            (i32.lt_s (local.get $i) (i32.const 0))
            (br_if $exit_str_loop)
            (i32.store8 
                (i32.add (local.get $rstart) (i32.sub (i32.sub (local.get $len) (i32.const 1)) (local.get $i)))
                (i32.load8_u (i32.add (local.get $start) (local.get $i)))
            )
            (local.set $i (i32.sub (local.get $i) (i32.const 1)))
            (br $str_loop)
        ))
        (local.get $reversed)
    )

    (func $__str_startsWith (export "__str_startsWith") (param $prefix i32) (param $str i32) (result i32)
        (local $prefixlen i32)
        (local $len i32)
        (local $prefixstart i32)
        (local $start i32)
        (local $i i32)
        (local.set $prefixlen (call $__str_length (local.get $prefix)))
        (local.set $len (call $__str_length (local.get $str)))
        (if (i32.lt_u (local.get $len) (local.get $prefixlen))
            (then
                (return (i32.const 0))
            )
        )
        (local.set $prefixstart (i32.add (local.get $prefix) (i32.const 4)))
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (loop $compare_loop (block $exit_compare_loop
            (i32.eq (local.get $i) (local.get $prefixlen))
            (br_if $exit_compare_loop)
            (i32.load8_u (i32.add (local.get $prefixstart) (local.get $i)))
            (i32.load8_u (i32.add (local.get $start) (local.get $i)))
            (i32.ne)
            if
                (return (i32.const 0))
            end
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $compare_loop)
        ))
        (i32.const 1)
    )

    (func $__str_endsWith (export "__str_endsWith") (param $suffix i32) (param $str i32) (result i32)
        (local $suffixlen i32)
        (local $len i32)
        (local $suffixstart i32)
        (local $start i32)
        (local $i i32)
        (local.set $suffixlen (call $__str_length (local.get $suffix)))
        (local.set $len (call $__str_length (local.get $str)))
        (if (i32.lt_u (local.get $len) (local.get $suffixlen))
            (then
                (return (i32.const 0))
            )
        )
        (local.set $suffixstart (i32.add (local.get $suffix) (i32.const 4)))
        (local.set $start (i32.add 
            (i32.add (local.get $str) (i32.const 4)) 
            (i32.sub (local.get $len) (local.get $suffixlen)))
        ) ;; str + 4 + (len - suffixlen)
        (loop $compare_loop (block $exit_compare_loop
            (i32.eq (local.get $i) (local.get $suffixlen))
            (br_if $exit_compare_loop)
            (i32.load8_u (i32.add (local.get $suffixstart) (local.get $i)))
            (i32.load8_u (i32.add (local.get $start) (local.get $i)))
            (i32.ne)
            if
                (return (i32.const 0))
            end
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $compare_loop)
        ))
        (i32.const 1)
    )

    (func $__str_toUpper (export "__str_toUpper") (param $str i32) (result i32)
        (local $len i32)
        (local $newStr i32)
        (local $newStart i32)
        (local $start i32)
        (local $char i32)
        (local $i i32)
        (local.set $len (call $__str_length (local.get $str)))
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (call $__malloc (i32.add (local.get $len) (i32.const 4)))
        (local.set $newStr)
        (i32.store (local.get $newStr) (local.get $len))
        (local.set $newStart (i32.add (local.get $newStr) (i32.const 4)))
        (loop $upperLoop (block $exit_upperLoop
            (i32.eq (local.get $i) (local.get $len))
            (br_if $exit_upperLoop)
            (local.set $char (i32.load8_u (i32.add (local.get $start) (local.get $i))))
            (if (i32.and
                    (i32.ge_u (local.get $char) (i32.const 97))
                    (i32.le_u (local.get $char) (i32.const 122))
                )
                (then
                    (i32.store8 (i32.add (local.get $newStart) (local.get $i))
                        (i32.sub 
                            (local.get $char)
                            (i32.const 32))
                    )
                )
                (else
                    (i32.store8 (i32.add (local.get $newStart) (local.get $i)) (local.get $char))
                )
            )
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $upperLoop)
        ))
        (local.get $newStr)
    )

    (func $__str_toLower (export "__str_toLower") (param $str i32) (result i32)
        (local $len i32)
        (local $newStr i32)
        (local $newStart i32)
        (local $start i32)
        (local $char i32)
        (local $i i32)
        (local.set $len (call $__str_length (local.get $str)))
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (call $__malloc (i32.add (local.get $len) (i32.const 4)))
        (local.set $newStr)
        (i32.store (local.get $newStr) (local.get $len))
        (local.set $newStart (i32.add (local.get $newStr) (i32.const 4)))
        (loop $upperLoop (block $exit_upperLoop
            (i32.eq (local.get $i) (local.get $len))
            (br_if $exit_upperLoop)
            (local.set $char (i32.load8_u (i32.add (local.get $start) (local.get $i))))
            (if (i32.and
                    (i32.ge_u (local.get $char) (i32.const 65))
                    (i32.le_u (local.get $char) (i32.const 90))
                )
                (then
                    (i32.store8 (i32.add (local.get $newStart) (local.get $i))
                        (i32.add 
                            (local.get $char)
                            (i32.const 32))
                    )
                )
                (else
                    (i32.store8 (i32.add (local.get $newStart) (local.get $i)) (local.get $char))
                )
            )
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $upperLoop)
        ))
        (local.get $newStr)
    )

    (func $__str_trim (export "__str_trim") (param $str i32) (result i32)
        (call $__str_trimStart (local.get $str))
        (call $__str_trimEnd)
    )

    (func $__str_trimStart (export "__str_trimStart") (param $str i32) (result i32)
        (local $len i32)
        (local $first_nonspace i32)
        (local $newStr i32)
        (local $newStart i32)
        (local $newLen i32)
        (local $start i32)
        (local $char i32)
        (local $i i32)
        (local.set $len (call $__str_length (local.get $str)))
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (loop $count_loop (block $exit_count_loop
            (i32.eq (local.get $i) (local.get $len))
            (br_if $exit_count_loop)
            (local.set $char (i32.load8_u (i32.add (local.get $start) (local.get $i))))
            (i32.or
                (i32.eq (local.get $char) (i32.const 9))
                (i32.or
                    (i32.eq (local.get $char) (i32.const 10))
                    (i32.or
                        (i32.eq (local.get $char) (i32.const 11))
                        (i32.or
                            (i32.eq (local.get $char) (i32.const 12))
                            (i32.or
                                (i32.eq (local.get $char) (i32.const 13))
                                (i32.eq (local.get $char) (i32.const 32))
                            )
                        )
                    )
                )
            )
            (i32.eqz)
            (br_if $exit_count_loop)
            (local.set $first_nonspace (i32.add (local.get $first_nonspace) (i32.const 1)))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $count_loop)
        ))
        (local.set $newLen (i32.sub (local.get $len) (local.get $first_nonspace)))
        (call $__malloc (i32.add (local.get $newLen) (i32.const 4)))
        (local.set $newStr)
        (i32.store (local.get $newStr) (local.get $newLen))
        (local.set $newStart (i32.add (local.get $newStr) (i32.const 4)))
        (memory.copy
            (local.get $newStart)
            (i32.add (local.get $start) (local.get $first_nonspace))
            (local.get $newLen)
        )
        (local.get $newStr)
    )

    (func $__str_trimEnd (export "__str_trimEnd") (param $str i32) (result i32)
        (local $len i32)
        (local $last_nonspace i32)
        (local $newStr i32)
        (local $newStart i32)
        (local $newLen i32)
        (local $start i32)
        (local $char i32)
        (local $i i32)
        (local.set $len (call $__str_length (local.get $str)))
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (local.set $i (i32.sub (local.get $len) (i32.const 1)))
        (local.set $last_nonspace (i32.sub (local.get $len) (i32.const 1)))
        (loop $count_loop (block $exit_count_loop
            (i32.lt_s (local.get $i) (i32.const 0))
            (br_if $exit_count_loop)
            (local.set $char (i32.load8_u (i32.add (local.get $start) (local.get $i))))
            (i32.or
                (i32.eq (local.get $char) (i32.const 9))
                (i32.or
                    (i32.eq (local.get $char) (i32.const 10))
                    (i32.or
                        (i32.eq (local.get $char) (i32.const 11))
                        (i32.or
                            (i32.eq (local.get $char) (i32.const 12))
                            (i32.or
                                (i32.eq (local.get $char) (i32.const 13))
                                (i32.eq (local.get $char) (i32.const 32))
                            )
                        )
                    )
                )
            )
            (i32.eqz)
            (br_if $exit_count_loop)
            (local.set $last_nonspace (i32.sub (local.get $last_nonspace) (i32.const 1)))
            (local.set $i (i32.sub (local.get $i) (i32.const 1)))
            (br $count_loop)
        ))
        (local.set $newLen (i32.sub (local.get $len) (i32.sub (i32.sub (local.get $len) (i32.const 1)) (local.get $last_nonspace))))
        (call $__malloc (i32.add (local.get $newLen) (i32.const 4)))
        (local.set $newStr)
        (i32.store (local.get $newStr) (local.get $newLen))
        (local.set $newStart (i32.add (local.get $newStr) (i32.const 4)))
        (memory.copy
            (local.get $newStart)
            (local.get $start)
            (local.get $newLen)
        )
        (local.get $newStr)
    )

    (func $__str_replace_char_char (export "__str_replace_char_char") (param $old i32) (param $new i32) (param $str i32) (result i32)
        (local $newStr i32)
        (local $len i32)
        (local $newLen i32)
        (local $replaced i32)
        (local $start i32)
        (local $newStart i32)
        (local $char i32)
        (local $i i32)
        (local.set $len (call $__str_length (local.get $str)))
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (if (i32.eq (local.get $old) (local.get $new))
            (then
                (call $__str_slice (local.get $str) (i32.const 0) (local.get $len)) ;; make a copy
                (return)
            )
        )
        (if (i32.eqz (local.get $len))
            (then 
                (if (i32.eqz (local.get $new))
                    (then
                        (local.set $newStr (call $__malloc (i32.const 4)))
                        (i32.store (local.get $newStr) (i32.const 0))
                        (return (local.get $newStr))
                    )
                    (else
                        (if (i32.eqz (local.get $old))
                            (then
                                (local.set $newStr (call $__malloc (i32.const 5)))
                                (i32.store (local.get $newStr) (i32.const 1))
                                (i32.store8 (i32.add (local.get $newStr) (i32.const 4)) (local.get $new))
                                (return (local.get $newStr))
                            )
                        )
                        
                    )
                )
            )
        )
        (if (i32.eqz (local.get $old))
            (then
                (call $__char_concat_str (local.get $new) (local.get $str))
                (return)
            )
        )
        (call $__malloc (i32.add (local.get $len) (i32.const 4)))
        (local.set $newStr)
        (i32.store (local.get $newStr) (local.get $len))
        (local.set $newStart (i32.add (local.get $newStr) (i32.const 4)))
        (loop $replace_loop (block $exit_replace_loop
            (i32.eq (local.get $i) (local.get $len))
            (br_if $exit_replace_loop)
            (i32.load8_u (i32.add (local.get $start) (local.get $i)))
            (local.set $char)
            (if (i32.and (i32.eq (local.get $char) (local.get $old)) (i32.eqz (local.get $replaced)))
                (then
                    (local.set $replaced (i32.const 1))
                    (if (i32.ne(local.get $new) (i32.const 0))
                        (then
                            (i32.store8 (i32.add (local.get $newStart) (local.get $i)) (local.get $new))
                        )
                    )
                )
                (else
                    (i32.store8 (i32.add (local.get $newStart) (local.get $i)) (local.get $char))
                )
            )
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $replace_loop)
        ))
        (local.get $newStr)
    )

    (func $__str_replaceAll_char_char (export "__str_replaceAll_char_char") (param $old i32) (param $new i32) (param $str i32) (result i32)
        (local $newStr i32)
        (local $len i32)
        (local $newLen i32)
        (local $start i32)
        (local $newStart i32)
        (local $char i32)
        (local $insert i32)
        (local $i i32)
        (local $j i32)
        (local.set $len (call $__str_length (local.get $str)))
        (local.set $newLen (local.get $len))
        (local.set $start (i32.add (local.get $str) (i32.const 4)))
        (if (i32.eq (local.get $old) (local.get $new))
            (then
                (call $__str_slice (local.get $str) (i32.const 0) (local.get $len)) ;; make a copy
                (return)
            )
        )
        (if (i32.eqz (local.get $len))
            (then 
                (if (i32.eqz (local.get $new))
                    (then
                        (local.set $newStr (call $__malloc (i32.const 4)))
                        (i32.store (local.get $newStr) (i32.const 0))
                        (return (local.get $newStr))
                    )
                    (else
                        (if (i32.eqz (local.get $old))
                            (then
                                (local.set $newStr (call $__malloc (i32.const 5)))
                                (i32.store (local.get $newStr) (i32.const 1))
                                (i32.store8 (i32.add (local.get $newStr) (i32.const 4)) (local.get $new))
                                (return (local.get $newStr))
                            )
                        )
                        
                    )
                )
            )
        )
        (if (i32.eqz (local.get $old))
            (then
                (local.set $insert (local.get $new))
                (local.set $newLen (i32.add (i32.mul (local.get $len) (i32.const 2)) (i32.const 1)))
            )
        )
        (call $__malloc (i32.add (local.get $newLen) (i32.const 4)))
        (local.set $newStr)
        (i32.store (local.get $newStr) (local.get $newLen))
        (local.set $newStart (i32.add (local.get $newStr) (i32.const 4)))
        (loop $replace_loop (block $exit_replace_loop
            (i32.eq (local.get $i) (local.get $len))
            (br_if $exit_replace_loop)
            (if (i32.ne (local.get $insert) (i32.const 0))
                (then
                    (i32.store8 (i32.add (local.get $newStart) (local.get $j)) (local.get $insert))
                    (local.set $j (i32.add (local.get $j) (i32.const 1)))
                )
            )
            (i32.load8_u (i32.add (local.get $start) (local.get $i)))
            (local.set $char)
            (if (i32.eq (local.get $char) (local.get $old))
                (then
                    (if (i32.ne(local.get $new) (i32.const 0))
                        (then
                            (i32.store8 (i32.add (local.get $newStart) (local.get $j)) (local.get $new))
                        )
                    )
                )
                (else
                    (i32.store8 (i32.add (local.get $newStart) (local.get $j)) (local.get $char))
                )
            )
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $replace_loop)
        ))
        (if (i32.ne (local.get $insert) (i32.const 0))
            (then
                (call $__str_concat_char (local.get $newStr) (local.get $insert))
                (return)
            )
        )
        (local.get $newStr)
    )